version: '3.8'
services:
  app: #studentsAPI
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /srv
    ports: #ホスト側:コンテナ側
      - 48080:8080
    tty: true
    volumes: #データ永続化
      - ./api:/srv:cached
    depends_on:
      db:
        condition: service_started #db起動後にappを起動
  db: # MySQL
    image: mysql:8.0
    volumes: #データ永続化(今回はSELECTのみだが今後の拡張に向け)
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports: #ホスト側:コンテナ側
      - "43306:3306"
    environment:
      MYSQL_DATABASE: school
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8